### ISSUE TITLE
[Question] How to use the local culture with a DateTime instance ?

### ISSUE THREAD

**Issue by LaurentDardenne** [SeeminglyScience/PSStringTemplate#5]
Hi,
the following code use the US culture on Windows  with French culture :
```Powershell
(Get-Culture).Name
#fr-FR

Invoke-StringTemplate -Definition "Outer=$([System.DateTime]::Now)`r`nInner= <Now>" -Parameters @{
 Now = [System.DateTime]::Now
}
#Outer=11/10/2017 12:39:32   ---> French
#Inner= 10/11/2017 12:39:32  ---> US
```
Is it possible to solve this problem other than with this code ?
```Powershell
... -Parameters @{
 Now = "$([System.DateTime]::Now)"
}
```

**Comment by SeeminglyScience** [comment]
Hmm this is really interesting.  What culture do you see when you run `Get-UICulture`?

I ask because if I set my culture with `Set-Culture fr-FR`  I get this:

```powershell
"$([DateTime]::Now)"
# returns 11/10/2017 07:32:30
[DateTime]::Now.ToString()
# returns 10/11/2017 07:32:30
```

That makes me think expandable string expressions use the current UI culture and the `ToString()` method uses the current thread culture.

There isn't a whole lot I can do about that specifically, but currently I pass the current culture to the template renderer directly.  Would adding a `Culture` parameter be a sufficient work around?

**Comment by LaurentDardenne** [comment]
_What culture do you see when you run Get-UICulture?_
fr-FR

_That makes me think expandable string expressions use the current UI culture and the ToString()_ method uses the current thread culture.
I think that the invariant culture is used. With a 'US Windows' it is the same. 

A other exemple
```Powershell
&{ "$(Get-Date)" }
#11/10/2017 14:53:57

$delegate= [System.Text.RegularExpressions.MatchEvaluator] {
  "$(Get-Date)"
}
$re = [regex] "[A-D]"

#use InvariantCulture -> US
$re.Replace("Now : A", $delegate)
#Now : 11/10/2017 14:54:52
```

I found this syntax, but that does not change anything:
```Powershell
Invoke-StringTemplate -Definition "Date=<Now; format='dd/MM/yyyy'>" -Parameters @{
 Now = [System.DateTime]::Now
}
```

_Would adding a Culture parameter be a sufficient work around?_
Before adding this, may be to [test](https://github.com/antlr/antlrcs/blob/7b8bd61b1a3a6e1d5b1d4c6cdacda2d0293c843e/Antlr4.Test.StringTemplate/TestRenderers.cs#L65) with API's in a Powershell console.
[It seems](https://github.com/antlr/antlrcs/blob/29db89e58792756f974d692f167eb4903bd8e353/Antlr3.StringTemplate/StringTemplateGroup.cs#L170) that the addition of a renderer is necessary.

**Comment by LaurentDardenne** [comment]
Tests around 'format' with renderer
```Powershell
import-module PSStringTemplate
#force loading Antlr4 assemblies

Invoke-StringTemplate -Definition 'Date=<Now; format="dd/MM/yyyy">' -Parameters @{
 Now = [System.DateTime]::Now
}

$definition= 'dateThing(created) ::= << date: <created; format="yyyy.MM.dd"> >>'
$group =[Antlr4.StringTemplate.TemplateGroupString]::new($Definition) 
$st = $group.GetInstanceOf("dateThing")
$date=[DateTime]::new(2005, 7, 5)
$Date
#mardi 5 juillet 2005 00:00:00

$st.Add("created", $Date)
$result = $st.Render()
 #expecting = " date: 2005.07.05 "

$result
#NOK
#'format' do not work
#date: 05/07/2005 00:00:00 

#Add renderer
$group.RegisterRenderer([DateTime], [Antlr4.StringTemplate.DateRenderer]::new())
$group.RegisterRenderer([DateTimeOffset], [Antlr4.StringTemplate.DateRenderer]::new())
$result = $st.Render()

$result
#OK
#'format' work as expected
# date: 2005.07.05 
```
Tests with specific cultures :
```Powershell
function Using-Culture ([System.Globalization.CultureInfo]$culture =(throw "USAGE: Using-Culture -Culture culture -Script {scriptblock}"),
                        [ScriptBlock]$script=(throw "USAGE: Using-Culture -Culture culture -Script {scriptblock}"))
{    
  #https://rkeithhill.wordpress.com/2009/10/21/windows-powershell-2-0-string-localization/
    $OldCulture = [System.Threading.Thread]::CurrentThread.CurrentCulture
    $OldUICulture = [System.Threading.Thread]::CurrentThread.CurrentUICulture
    try {
        [System.Threading.Thread]::CurrentThread.CurrentCulture = $culture
        [System.Threading.Thread]::CurrentThread.CurrentUICulture = $culture        
        Invoke-Command $script    
    }    
    finally {        
        [System.Threading.Thread]::CurrentThread.CurrentCulture = $OldCulture        
        [System.Threading.Thread]::CurrentThread.CurrentUICulture = $OldUICulture    
    }    
}
$Test={
  $definition= 'dateThing(created) ::= << date: <created; format="dddd dd MMMM yyyy"> >>'
  $group =[Antlr4.StringTemplate.TemplateGroupString]::new($Definition)
  $group.RegisterRenderer([DateTime], [Antlr4.StringTemplate.DateRenderer]::new())
  $group.RegisterRenderer([DateTimeOffset], [Antlr4.StringTemplate.DateRenderer]::new()) 
  $st = $group.GetInstanceOf("dateThing")
  $st.Add("created", [DateTime]::new(2005, 7, 5))> $null
  $st.Render()
}
.$Test
#OK
#date: mardi 05 juillet 2005

Using-Culture de-DE $Test
#date: Dienstag 05 Juli 2005

Using-Culture en-US $Test
#date: Tuesday 05 July 2005
```

**Comment by SeeminglyScience** [comment]
Ah yes adding the renderer is a much better fix, thank you so much for looking into that :)

Changes are made for this and enabling static properties, just need to write tests and I should have a release with the changes by the end of the day.

**Comment by LaurentDardenne** [comment]
Do changes make it possible to use a personal rendering?

**Comment by SeeminglyScience** [comment]
This change will just be adding the `DateRenderer`, which would allow using the format operator for dates like shown in this thread.

I do plan on adding a way to apply custom renderers, but that's a little bit more difficult to make approachable from PowerShell.  I'll open a separate issue for that, and go into more detail there.

**Comment by SeeminglyScience** [comment]
Version 0.2.0 is now available in the gallery and should solve the original issue, but give it a try and feel free to reopen the issue if it doesn't work for your use case!

I opened a separate issue (#12) to track custom renderers including implementation pit falls and ideas.  Thanks again for the help, greatly appreciated!

**Comment by LaurentDardenne** [comment]
_Version 0.2.0 is now available in the gallery_
Thank you.
