### ISSUE TITLE
Add a parameter to configure attribute delimiter

### ISSUE THREAD

**Issue by LaurentDardenne** [SeeminglyScience/PSStringTemplate#6]
This [example](https://theantlrguy.atlassian.net/wiki/spaces/ST/pages/1409116/Five+minute+Introduction) (number 4 _Create and use a template from a file_) do not works :
```powershell
import-module PSStringTemplate
$OriginalDefinition=@'
<html>
    <head>
       <title>$title$</title>
    </head>
    <body>
       <p>Hello again, $name$ !</p>
       <p>Greetings to your friends $rest(friends); separator=", "$</p>
   </body>
</html>
'@
Invoke-StringTemplate -Definition $OriginalDefinition -Parameters @{
 Title = 'My Title'
 name='My name'
}
#$title$
#Hello again, $name$ !
#Greetings to your friends $rest(friends); separator=", "$
```
In this case it is correct **Dollar** is not the delimiter, but the html balise causes a collision.
How to generate a htlm or xml template ?
 
The addition of [parameters](https://github.com/antlr/antlrcs/blob/29db89e58792756f974d692f167eb4903bd8e353/Antlr4.StringTemplate/TemplateGroupString.cs#L58) _-Delimiter @{Start='%';End='%'}_ can it facilitate the creation of an HTML or XML template ?
```powershell
$Title='PSVariable Title'
$OriginalDefinition=@"
<html>
    <head>
       <title>$title</title>
    </head>
    <body>
       <p>Hello again, %name% !</p>
       <p>Greetings to your friends %rest(friends); separator=", "%</p>
   </body>
</html>
"@

Invoke-StringTemplate -Definition $OriginalDefinition -Delimiter @{Start='%';End='%'} -Parameters @{
 name='My name'
}
```

**Comment by SeeminglyScience** [comment]
Yeah, there should definitely be a `Delimiter` parameter.  I'm torn between the following syntax:

1. `-Delimiter @{ Start = '%'; End = '%' }`
1. `-Delimiter '%', '%'`
1. `-StartDelimiter '%' -EndDelimiter '%'`

I'm leaning towards number two, I feel like that one is probably the easiest to "guess" into correctly, especially if you want the same delimiter for start and end.

Also as a work around for now, this is currently possible with template groups:

```powershell
$group = New-StringTemplateGroup -Definition '
delimiters "$", "$"

myHtmlPage(title, name, friends) ::= <<
<html>
    <head>
       <title>$title$</title>
    </head>
    <body>
       <p>Hello again, $name$ !</p>
       <p>Greetings to your friends $rest(friends); separator=", "$</p>
   </body>
</html>
>>
'

$group | Invoke-StringTemplate -Name myHtmlPage -Parameters @{
    title = 'myTitle'
    name = 'John Smith'
    friends = 'Bob', 'Bill', 'Ted'
}
```

**Comment by LaurentDardenne** [comment]
_Also as a work around for now, this is currently possible with template groups_
Thanks you.
I have not read all the [documentation](https://github.com/antlr/stringtemplate4/blob/master/doc/groups.md) yet

For this syntax 
```powershell
-Delimiter @{ Start = '%'; End = '%' }
```
I was thinking of options
```powershell
-Options @ {Start = '%'; End = '%'}
```
but I do not know if there may be other.

I find this syntax concise but for advanced use because in my opinion it requires to know the functioning of StringTemplate4.
```powershell
-Delimit '%', '%'
```
This one is verbose :
```powershell
     -StartDelimiter '%' -EndDelimit '%'
```     
but preferable for the discovery, moreover it is explicit.
Or
```powershell
    -Delimiter '%' #equal  to -StartDelimiter '%' -EndDelimit '%'
      #mutually exclusive
    -StartDelimiter ':' -EndDelimit '*'
```

**Comment by SeeminglyScience** [comment]
Excellent point about discovery, I agree 100%.

So the current plan is to have a `StartDelimiter` parameter with an alias of `Delimiter` and an `EndDelimiter` parameter. 

* If `StartDelimiter` is specified when `EndDelimiter` is not, then it will be assumed that the they are the same.
* If `EndDelimiter` is specified when `StartDelimiter` is not, an error will be thrown. 
* If neither are specified, no attempt will be made to set the delimiter so there are no issues if the delimiter is specified in a group definition.

**Comment by LaurentDardenne** [comment]
_So the current plan is to have a StartDelimiter parameter with an alias of Delimiter and an EndDelimiter parameter._
Unlike a set of parameters, the use of an alias does not help to visualize the use cases: :
```powershell
Function New-StringTemplateGroup2 {
[CmdletBinding(DefaultParameterSetName='ByTemplateDefinition')]
param(
    [Parameter(Mandatory=$true)]
    [ValidateNotNullOrEmpty()]
    [string]
    ${Definition},
    
     [Parameter(Mandatory=$true,ParameterSetName='Delimiter')]
    ${Delimiter},

    [Parameter(Mandatory=$true,ParameterSetName='Delimiters')]
    #[Alias('Delimiter')]
    ${StartDelimiter},

    [Parameter(Mandatory=$true,ParameterSetName='Delimiters')]
    ${EndDelimiter})

  process
  {
  }
}
New-StringTemplateGroup2 -?

# NAME
#     New-StringTemplateGroup2
# 
# SYNTAX
#     New-StringTemplateGroup2 -Definition <string>  [<CommonParameters>]
# 
#        !!! With an alias this line is absent
#     New-StringTemplateGroup2 -Definition <string> -Delimiter <Object>  [<CommonParameters>]    
# 
#     New-StringTemplateGroup2 -Definition <string> -StartDelimiter <Object> -EndDelimiter <Object>  [<CommonParameters>]
```
Maybe there is another case, use a 'delimiters' setting with -Delimiter or -StartDelimiter  :
```powershell
$definition=@'
delimiters "$", "$"

myHtmlPage(title, name, friends) ::= <<
<html>
    <head>
       <title>$title$</title>
    </head>
    <body>
       <p>Hello again, $name$ !</p>
       <p>Greetings to your friends $rest(friends); separator=", "$</p>
   </body>
</html>
>>
'@

[char]$Delimiter='%'
$group =[Antlr4.StringTemplate.TemplateGroupString]::new('SourceName',$Definition,$Delimiter,$Delimiter)
$group|Select Delim*
# DelimiterStartChar DelimiterStopChar
# ------------------ -----------------
#                  %                 %

$st = $group.GetInstanceOf("myHtmlPage")
$st.Add('title','Test')
$st.Render()
$group|Select Delim*
# DelimiterStartChar DelimiterStopChar
# ------------------ -----------------
#                  $                 $
```
The keyword 'delimiters' overwrite silently the parameter '-Delimiter'.
But it seems that [each group](https://github.com/antlr/antlrcs/blob/master/Antlr4.StringTemplate/Template.cs#L163) can redeclare the delimiters.

**Comment by SeeminglyScience** [comment]
> Unlike a set of parameters, the use of an alias does not help to visualize the use cases

While I agree, I think the price is worth it to avoid the added complexity.  I'd like to have these parameters in `Invoke-StringTemplate` as well and they already have parameter sets, so integrating these as well would be messy.  Also in this instance the lack of discoverability would just result in specifying both a start and end delimiter.  I'm okay with causing the user to be slightly more explicit then they may need to be in this case.
